### PR TITLE
Add convenience method populateWithAvailableLanguages(List<String>)

### PR DESCRIPTION
**Pull request by dacdave**
Closes issue #36.

### CODE REVIEW

**Comment by dacdave** [comment]
Add a new method to the LRS interface, and its RemoteLRS implementation. The new method is called retrieveActivity. It sends a GET to the "activities" endpoint and returns the canonical description of the activity found here, if any.

**Comment by garemoko** [comment]
Thanks for this @dcdave!

There's also a related issue on TinCanPHP with some code: https://github.com/RusticiSoftware/TinCanPHP/issues/24

We should agree on the method name and parameters.

**Comment by brianjmiller** [comment]
Let's wrap up the discussion in https://github.com/RusticiSoftware/TinCanPHP/issues/24 and then see where this needs to land.

**Comment by brianjmiller** [comment]
This languished long enough that I felt bad about sending it back with review comments, so I just made what would be the required changes and have set it up pending as #51. Effectively `.retrievePerson` and `.retrieveActivity` needed new LRS response types so that they could store proper content bodies based on what is returned from an LRS. That included adding a new `Person` object and adjusting the RemoteLRS implementation to not call the `getDocument` method. The existing implementation would have worked I guess because the used response types are so generic. These changes bring the library more inline with the original PHP approach and I think are similar to the approach used elsewhere in this lib. The changes once merged will go out in the next minor version release which will quickly be followed by a major version release for JDK 8.

**Pull request closed without merging**
